[Icon Theme]
Name=Kaze-Colors
Comment=Color accent support for Kaze-dark icon theme
Inherits=Kaze-light,gnome,hicolor

Example=x-directory-normal

FollowsColorScheme=true

Directories=64x64/apps,64x64/places,24x24/places,24x24/status,24x24/devices,24x24/actions,24x24/apps

[64x64/apps]
Context=Applications
Size=64
MinSize=64
MaxSize=512
Type=Scalable

[64x64/places]
Context=Places
Size=64
MinSize=64
MaxSize=512
Type=Scalable

[24x24/places]
Context=Places
Size=24
Type=Fixed

[24x24/status]
Context=Status
Size=24
Type=Fixed

[24x24/devices]
Context=Devices
Size=24
Type=Fixed

[24x24/actions]
Context=Actions
Size=24
Type=Fixed

[24x24/apps]
Context=Apps
Size=24
Type=Fixed


